import argparse
import json
import os
import re
import sys
import runpy
from typing import Dict, Any, List, Tuple
from pprint import pformat

ALLOWED_CATEGORIES = {"Robot Initial States", "Camera Viewpoints"}

def _strip_json_comments(text: str) -> str:
    # Remove // line comments and inline comments; keep URLs naive-safe by only removing // after optional leading spaces
    lines = []
    for line in text.splitlines():
        # Remove full-line comments
        if re.match(r'^\s*//', line):
            continue
        # Remove inline comments: everything after //, unless inside quotes (simple heuristic)
        # This is conservative and should work for this dataset.
        parts = re.split(r'(?<!:)//', line, maxsplit=1)
        lines.append(parts[0])
    return "\n".join(lines)

def load_classification(path: str) -> Dict[str, List[Dict[str, Any]]]:
    with open(path, "r", encoding="utf-8") as f:
        raw = f.read()
    cleaned = _strip_json_comments(raw)
    data = json.loads(cleaned)
    # Expect a dict of suite_name -> list of {"category": "..."} matching the suite's task ordering
    return {k: v for k, v in data.items() if isinstance(v, list)}

def load_original_task_map(py_path: str) -> (str, Dict[str, List[Any]]):
    # Execute the python file in an isolated namespace to capture variables
    namespace = runpy.run_path(py_path)
    # Heuristically choose the main dict variable mapping suite -> list-of-tasks
    classification_like_keys = {"libero_spatial", "libero_object", "libero_goal", "libero_10"}
    candidates = []
    for name, val in namespace.items():
        if isinstance(val, dict) and val:
            # keys must be strings
            if not all(isinstance(k, str) for k in val.keys()):
                continue
            # values should be lists
            if not all(isinstance(v, list) for v in val.values()):
                continue
            # score by overlap with expected suite names
            score = len(set(val.keys()) & classification_like_keys)
            candidates.append((score, name, val))
    if not candidates:
        raise RuntimeError(f"No valid suite->tasks dict found in {py_path}")
    # Pick the one with the highest overlap score; fall back to the largest dict
    candidates.sort(key=lambda x: (x[0], len(x[2])), reverse=True)
    _, var_name, task_map = candidates[0]
    return var_name, task_map

def filter_task_map_by_categories(
    task_map: Dict[str, List[Any]],
    classification: Dict[str, List[Dict[str, Any]]],
    allowed_categories: set,
) -> Tuple[Dict[str, List[Any]], Dict[str, List[int]]]:
    # Preserve all suites (even if empty after filtering)
    filtered: Dict[str, List[Any]] = {}
    kept_indices_by_suite: Dict[str, List[int]] = {}
    for suite, tasks in task_map.items():
        labels = classification.get(suite, [])
        n = min(len(tasks), len(labels)) if isinstance(labels, list) else 0
        keep_indices = [
            i for i in range(n)
            if isinstance(labels[i], dict) and labels[i].get("category") in allowed_categories
        ]
        kept_indices_by_suite[suite] = keep_indices
        filtered[suite] = [tasks[i] for i in keep_indices]
    return filtered, kept_indices_by_suite

def write_spatial_task_map(output_path: str, var_name: str, filtered_map: Dict[str, List[Any]]) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    header = "# Auto-generated by scripts/prepare_spatial_eval.py; do not edit.\n"
    header += "# Contains only tasks whose categories are Robot Initial States or Camera Viewpoints.\n"
    body = f"{var_name} = {pformat(filtered_map, width=100, sort_dicts=True)}\n"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(body)

def _task_name(task: Any) -> str:
    # Best-effort extraction of a human-readable name from task entry
    if isinstance(task, dict) and "name" in task and isinstance(task["name"], str):
        return task["name"]
    if isinstance(task, str):
        return task
    name_attr = getattr(task, "name", None)
    if isinstance(name_attr, str):
        return name_attr
    qualname = getattr(task, "__name__", None)
    if isinstance(qualname, str):
        return qualname
    return str(task)

def build_filtered_classification(
    suites: List[str],
    classification: Dict[str, List[Dict[str, Any]]],
    kept_indices_by_suite: Dict[str, List[int]],
    task_map: Dict[str, List[Any]],
) -> Dict[str, List[Dict[str, Any]]]:
    result: Dict[str, List[Dict[str, Any]]] = {}
    for suite in suites:
        labels = classification.get(suite, [])
        keep = kept_indices_by_suite.get(suite, [])
        tasks = task_map.get(suite, [])
        # Reassign ids sequentially after filtering and include name
        result[suite] = [
            {
                "id": i_new,
                "name": _task_name(tasks[i_old]) if i_old < len(tasks) else None,
                "category": (labels[i_old].get("category") if i_old < len(labels) else None),
            }
            for i_new, i_old in enumerate(keep)
        ]
    return result

def write_filtered_classification_json(output_path: str, data: Dict[str, List[Dict[str, Any]]]) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

def main():
    parser = argparse.ArgumentParser(description="Prepare spatial eval task map (Robot Initial States + Camera Viewpoints).")
    parser.add_argument(
        "--benchmark-dir",
        default="/data/nfs/px/Projects/gamma/third_party/LIBERO-plus/libero/libero/benchmark",
        help="Directory containing task_classification.json and libero_suite_task_map.py",
    )
    parser.add_argument(
        "--categories",
        nargs="+",
        default=sorted(ALLOWED_CATEGORIES),
        help="Categories to keep (default: Robot Initial States, Camera Viewpoints)",
    )
    parser.add_argument(
        "--out-classification",
        default="task_classification_spatial.json",
        help="Output filename for filtered classification JSON (default: task_classification_spatial.json)",
    )
    args = parser.parse_args()

    bench_dir = os.path.abspath(args.benchmark_dir)
    cls_path = os.path.join(bench_dir, "task_classification.json")
    src_map_path = os.path.join(bench_dir, "libero_suite_task_map.py")
    out_map_path = os.path.join(bench_dir, "libero_suite_task_map_spatial.py")
    out_cls_path = os.path.join(bench_dir, args.out_classification)

    if not os.path.isfile(cls_path):
        print(f"Missing classification: {cls_path}", file=sys.stderr)
        sys.exit(1)
    if not os.path.isfile(src_map_path):
        print(f"Missing source task map: {src_map_path}", file=sys.stderr)
        sys.exit(1)

    classification = load_classification(cls_path)
    var_name, task_map = load_original_task_map(src_map_path)
    filtered, kept_indices = filter_task_map_by_categories(task_map, classification, set(args.categories))

    # Always write outputs; suites with no matches will be empty lists
    write_spatial_task_map(out_map_path, var_name, filtered)

    # Build and write the filtered classification JSON with reassigned ids and names
    suites = list(task_map.keys())
    filtered_cls = build_filtered_classification(suites, classification, kept_indices, task_map)
    write_filtered_classification_json(out_cls_path, filtered_cls)

    # Minimal summary
    totals = {k: len(v) for k, v in filtered.items()}
    print(f"Wrote {out_map_path}")
    print(f"Wrote {out_cls_path}")
    print(f"Kept suites: {', '.join(sorted(filtered.keys()))}")
    print("Counts per suite:", totals)

if __name__ == "__main__":
    main()
